<?php

use Carbon\Carbon;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCountriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->increments('id');
            $table->string('code', 12);
            $table->string('name', 255);
            $table->timestamps();

            $table->softDeletes();
        });

        $countries = array(
            array('id' => '1',  	'code' => 'AD', 'name' => 'Andorra',                        				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '2',  	'code' => 'AE', 'name' => 'United Arab Emirates',           				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '3',  	'code' => 'AF', 'name' => 'Afghanistan',                    				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '4',  	'code' => 'AG', 'name' => 'Antigua and Barbuda',            				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '5',  	'code' => 'AI', 'name' => 'Anguilla',                       				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '6',  	'code' => 'AL', 'name' => 'Albania',                        				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '7',  	'code' => 'AM', 'name' => 'Armenia',                        				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '8',  	'code' => 'AN', 'name' => 'Netherlands Antilles',           				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '9',  	'code' => 'AO', 'name' => 'Angola',                         				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '10', 	'code' => 'AQ', 'name' => 'Antarctica',                     				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '11', 	'code' => 'AR', 'name' => 'Argentina',                      				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '12', 	'code' => 'AS', 'name' => 'American Samoa',                 				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '13', 	'code' => 'AT', 'name' => 'Austria',                        				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '14', 	'code' => 'AU', 'name' => 'Australia',                      				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '15', 	'code' => 'AW', 'name' => 'Aruba',                          				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '16', 	'code' => 'AX', 'name' => 'Aland Islands',                  				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '17', 	'code' => 'AZ', 'name' => 'Azerbaijan',                     				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '18', 	'code' => 'BA', 'name' => 'Bosnia and Herzegovina',         				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '19', 	'code' => 'BB', 'name' => 'Barbados',                       				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '20', 	'code' => 'BD', 'name' => 'Bangladesh',                     				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '21', 	'code' => 'BE', 'name' => 'Belgium',                        				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '22', 	'code' => 'BF', 'name' => 'Burkina Faso',                   				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '23', 	'code' => 'BG', 'name' => 'Bulgaria',                       				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '24', 	'code' => 'BH', 'name' => 'Bahrain',                        				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '25', 	'code' => 'BI', 'name' => 'Burundi',                        				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '26', 	'code' => 'BJ', 'name' => 'Benin',                          				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '27', 	'code' => 'BL', 'name' => 'Saint Barthélemy',               				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '28', 	'code' => 'BM', 'name' => 'Bermuda',                        				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '29', 	'code' => 'BN', 'name' => 'Brunei',                         				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '30', 	'code' => 'BO', 'name' => 'Bolivia',                        				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '31', 	'code' => 'BQ', 'name' => 'Bon  Saint Eustatius and Saba',  				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '32', 	'code' => 'BR', 'name' => 'Brazil',                         				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '33', 	'code' => 'BS', 'name' => 'Bahamas',                        				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '34', 	'code' => 'BT', 'name' => 'Bhutan',                         				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '35', 	'code' => 'BV', 'name' => 'Bouvet Island',                  				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '36', 	'code' => 'BW', 'name' => 'Botswana',										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '37', 	'code' => 'BY', 'name' => 'Belarus',                        				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '38', 	'code' => 'BZ', 'name' => 'Belize',                         				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '39', 	'code' => 'CA', 'name' => 'Canada',                         				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '40', 	'code' => 'CC', 'name' => 'Cocos Islands',                  				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '41', 	'code' => 'CD', 'name' => 'Democratic Republic of the Congo',   			'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '42', 	'code' => 'CF', 'name' => 'Central African Republic',           			'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '43', 	'code' => 'CG', 'name' => 'Republic of the Congo',  						'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '44', 	'code' => 'CH', 'name' => 'Switzerland',    								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '45', 	'code' => 'CI', 'name' => 'Ivory Coast',    								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '46', 	'code' => 'CK', 'name' => 'Cook Islands',   								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '47', 	'code' => 'CL', 'name' => 'Chile',  										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '48', 	'code' => 'CM', 'name' => 'Cameroon',   									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '49', 	'code' => 'CN', 'name' => 'China',  										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '50', 	'code' => 'CO', 'name' => 'Colombia',   									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '51', 	'code' => 'CR', 'name' => 'Costa Rica', 									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '52', 	'code' => 'CS', 'name' => 'Serbia and Montenegro', 		 					'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '53', 	'code' => 'CU', 'name' => 'Cuba',   										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '54', 	'code' => 'CV', 'name' => 'Cape Verde', 									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '55', 	'code' => 'CW', 'name' => 'Curaçao',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '56', 	'code' => 'CX', 'name' => 'Christmas Island',   							'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '57', 	'code' => 'CY', 'name' => 'Cyprus', 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '58', 	'code' => 'CZ', 'name' => 'Czech Republic', 								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '59', 	'code' => 'DE', 'name' => 'Germany',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '60', 	'code' => 'DJ', 'name' => 'Djibouti',   									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '61', 	'code' => 'DK', 'name' => 'Denmark',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '62', 	'code' => 'DM', 'name' => 'Dominica',   									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '63', 	'code' => 'DO', 'name' => 'Dominican Republic', 							'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '64', 	'code' => 'DZ', 'name' => 'Algeria',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '65', 	'code' => 'EC', 'name' => 'Ecuador',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '66', 	'code' => 'EE', 'name' => 'Estonia',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '67', 	'code' => 'EG', 'name' => 'Egypt',  										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '68', 	'code' => 'EH', 'name' => 'Western Sahara',									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '69', 	'code' => 'ER', 'name' => 'Eritrea',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '70', 	'code' => 'ES', 'name' => 'Spain',  										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '71', 	'code' => 'ET', 'name' => 'Ethiopia',   									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '72', 	'code' => 'FI', 'name' => 'Finland',   	 									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '73', 	'code' => 'FJ', 'name' => 'Fiji',  	 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '74', 	'code' => 'FK', 'name' => 'Falkland Islands',   							'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '75', 	'code' => 'FM', 'name' => 'Micronesia', 									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '76', 	'code' => 'FO', 'name' => 'Faroe Islands',  								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '77', 	'code' => 'FR', 'name' => 'France', 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '78', 	'code' => 'GA', 'name' => 'Gabon',  										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '79', 	'code' => 'GB', 'name' => 'United Kingdom', 								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '80', 	'code' => 'GD', 'name' => 'Grenada',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '81', 	'code' => 'GE', 'name' => 'Georgia',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '82', 	'code' => 'GF', 'name' => 'French Guiana',  								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '83', 	'code' => 'GG', 'name' => 'Guernsey',   									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '84', 	'code' => 'GH', 'name' => 'Ghana',  										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '85', 	'code' => 'GI', 'name' => 'Gibraltar',  									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '86', 	'code' => 'GL', 'name' => 'Greenland',  									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '87', 	'code' => 'GM', 'name' => 'Gambia', 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '88', 	'code' => 'GN', 'name' => 'Guinea', 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '89', 	'code' => 'GP', 'name' => 'Guadeloupe', 									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '90', 	'code' => 'GQ', 'name' => 'Equatorial Guinea',  							'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '91', 	'code' => 'GR', 'name' => 'Greece', 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '92', 	'code' => 'GS', 'name' => 'South Georgia and the South Sandwich Islands',	'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '93', 	'code' => 'GT', 'name' => 'Guatemala',										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '94', 	'code' => 'GU', 'name' => 'Guam',											'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '95', 	'code' => 'GW', 'name' => 'Guinea-Bissau',									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '96', 	'code' => 'GY', 'name' => 'Guyana',											'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '97', 	'code' => 'HK', 'name' => 'Hong Kong',										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '98', 	'code' => 'HM', 'name' => 'Heard Island and McDonald Islands',				'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '99', 	'code' => 'HN', 'name' => 'Honduras',										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '100',    'code' => 'HR', 'name' => 'Croatia',										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '101',    'code' => 'HT', 'name' => 'Haiti',											'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '102',    'code' => 'HU', 'name' => 'Hungary',										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '103',    'code' => 'ID', 'name' => 'Indonesia',										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '104',    'code' => 'IE', 'name' => 'Ireland',										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '105',    'code' => 'IL', 'name' => 'Israel',											'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '106',    'code' => 'IM', 'name' => 'Isle of Man',									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '107',    'code' => 'IN', 'name' => 'India',											'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '108',    'code' => 'IO', 'name' => 'British Indian Ocean Territory',					'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '109',    'code' => 'IQ', 'name' => 'Iraq',											'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '110',    'code' => 'IR', 'name' => 'Iran',											'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '111',    'code' => 'IS', 'name' => 'Iceland',										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '112',    'code' => 'IT', 'name' => 'Italy',											'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '113',    'code' => 'JE', 'name' => 'Jersey',											'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '114',    'code' => 'JM', 'name' => 'Jamaica', 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '115',    'code' => 'JO', 'name' => 'Jordan',											'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '116',    'code' => 'JP', 'name' => 'Japan',											'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '117',    'code' => 'KE', 'name' => 'Kenya',											'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '118',    'code' => 'KG', 'name' => 'Kyrgyzstan', 									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '119',    'code' => 'KH', 'name' => 'Cambodia',   									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '120',    'code' => 'KI', 'name' => 'Kiribati',   									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '121',    'code' => 'KM', 'name' => 'Comoros',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '122',    'code' => 'KN', 'name' => 'Saint Kitts and Nevis',  						'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '123',    'code' => 'KP', 'name' => 'North Korea',    								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '124',    'code' => 'KR', 'name' => 'South Korea',    								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '125',    'code' => 'KW', 'name' => 'Kuwait', 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '126',    'code' => 'KY', 'name' => 'Cayman Islands', 								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '127',    'code' => 'KZ', 'name' => 'Kazakhstan', 									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '128',    'code' => 'LA', 'name' => 'Laos',   										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '129',    'code' => 'LB', 'name' => 'Lebanon',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '130',    'code' => 'LC', 'name' => 'Saint Lucia',    								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '131',    'code' => 'LI', 'name' => 'Liechtenstein',  								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '132',    'code' => 'LK', 'name' => 'Sri Lanka',  									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '133',    'code' => 'LR', 'name' => 'Liberia',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '134',    'code' => 'LS', 'name' => 'Lesotho',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '135',    'code' => 'LT', 'name' => 'Lithuania',  									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '136',    'code' => 'LU', 'name' => 'Luxembourg', 									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '137',    'code' => 'LV', 'name' => 'Latvia', 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '138',    'code' => 'LY', 'name' => 'Libya',  										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '139',    'code' => 'MA', 'name' => 'Morocco',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '140',    'code' => 'MC', 'name' => 'Monaco', 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '141',    'code' => 'MD', 'name' => 'Moldova',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '142',    'code' => 'ME', 'name' => 'Montenegro', 									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '143',    'code' => 'MF', 'name' => 'Saint Martin',									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '144',    'code' => 'MG', 'name' => 'Madagascar', 									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '145',    'code' => 'MH', 'name' => 'Marshall Islands',   							'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '146',    'code' => 'MK', 'name' => 'Macedonia', 	 									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '147',    'code' => 'ML', 'name' => 'Mali',   										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '148',    'code' => 'MM', 'name' => 'Myanmar',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '149',    'code' => 'MN', 'name' => 'Mongolia',   									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '150',    'code' => 'MO', 'name' => 'Macao',  										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '151',    'code' => 'MP', 'name' => 'Northern Mariana Islands',   					'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '152',    'code' => 'MQ', 'name' => 'Martinique', 									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '153',    'code' => 'MR', 'name' => 'Mauritania', 									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '154',    'code' => 'MS', 'name' => 'Montserrat', 									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '155',    'code' => 'MT', 'name' => 'Malta',  										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '156',    'code' => 'MU', 'name' => 'Mauritius',  									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '157',    'code' => 'MV', 'name' => 'Maldives',   									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '158',    'code' => 'MW', 'name' => 'Malawi',				 							'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '159',    'code' => 'MX', 'name' => 'Mexico', 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '160',    'code' => 'MY', 'name' => 'Malaysia',   									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '161',    'code' => 'MZ', 'name' => 'Mozambique', 									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '162',    'code' => 'NA', 'name' => 'Namibia',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '163',    'code' => 'NC', 'name' => 'New Caledonia',  								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '164',    'code' => 'NE', 'name' => 'Niger',  										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '165',    'code' => 'NF', 'name' => 'Norfolk Island', 								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '166',    'code' => 'NG', 'name' => 'Nigeria',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '167',    'code' => 'NI', 'name' => 'Nicaragua',  									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '168',    'code' => 'NL', 'name' => 'Netherlands',    								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '169',    'code' => 'NO', 'name' => 'Norway', 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '170',    'code' => 'NP', 'name' => 'Nepal',  										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '171',    'code' => 'NR', 'name' => 'Nauru',  										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '172',    'code' => 'NU', 'name' => 'Niue',   										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '173',    'code' => 'NZ', 'name' => 'New Zealand',    								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '174',    'code' => 'OM', 'name' => 'Oman',   										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '175',    'code' => 'PA', 'name' => 'Panama',	 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '176',    'code' => 'PE', 'name' => 'Peru',   										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '177',    'code' => 'PF', 'name' => 'French Polynesia',   							'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '178',    'code' => 'PG', 'name' => 'Papua New Guinea',   							'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '179',    'code' => 'PH', 'name' => 'Philippines',    								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '180',    'code' => 'PK', 'name' => 'Pakistan',   									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '181',    'code' => 'PL', 'name' => 'Poland', 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '182',    'code' => 'PM', 'name' => 'Saint Pierre and Miquelon',						'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '183',    'code' => 'PN', 'name' => 'Pitcairn',   									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '184',    'code' => 'PR', 'name' => 'Puerto Rico',    								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '185',    'code' => 'PS', 'name' => 'Palestinian Territory',  						'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '186',    'code' => 'PT', 'name' => 'Portugal',   									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '187',    'code' => 'PW', 'name' => 'Palau',  										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '188',    'code' => 'PY', 'name' => 'Paraguay',   									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '189',    'code' => 'QA', 'name' => 'Qatar',  										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '190',    'code' => 'RE', 'name' => 'Reunion',   	 									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '191',    'code' => 'RO', 'name' => 'Romania',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '192',    'code' => 'RS', 'name' => 'Serbia', 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '193',    'code' => 'RU', 'name' => 'Russia', 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '194',    'code' => 'RW', 'name' => 'Rwanda', 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '195',    'code' => 'SA', 'name' => 'Saudi Arabia',   								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '196',    'code' => 'SB', 'name' => 'Solomon Islands',    							'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '197',    'code' => 'SC', 'name' => 'Seychelles', 									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '198',    'code' => 'SD', 'name' => 'Sudan',  										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '199',    'code' => 'SE', 'name' => 'Sweden', 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '200',    'code' => 'SG', 'name' => 'Singapore',  									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '201',    'code' => 'SH', 'name' => 'Saint Helena',   								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '202',    'code' => 'SI', 'name' => 'Slovenia',   									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '203',    'code' => 'SJ', 'name' => 'Svalbard and Jan Mayen', 						'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '204',    'code' => 'SK', 'name' => 'Slovakia',   									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '205',    'code' => 'SL', 'name' => 'Sierra Leone',   								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '206',    'code' => 'SM', 'name' => 'San Marino', 									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '207',    'code' => 'SN', 'name' => 'Senegal',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '208',    'code' => 'SO', 'name' => 'Somalia',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '209',    'code' => 'SR', 'name' => 'Suriname',   									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '210',    'code' => 'SS', 'name' => 'South Sudan',    								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '211',    'code' => 'ST', 'name' => 'Sao Tome and Principe',  						'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '212',    'code' => 'SV', 'name' => 'El Salvador',    								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '213',    'code' => 'SX', 'name' => 'Sint Maarten',   								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '214',    'code' => 'SY', 'name' => 'Syria',  										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '215',    'code' => 'SZ', 'name' => 'Swaziland',  									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '216',    'code' => 'TC', 'name' => 'Turks and Caicos Islands',   					'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '217',    'code' => 'TD', 'name' => 'Chad',   										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '218',    'code' => 'TF', 'name' => 'French Southern Territories',					'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '219',    'code' => 'TG', 'name' => 'Togo',   										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '220',    'code' => 'TH', 'name' => 'Thailand',   									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '221',    'code' => 'TJ', 'name' => 'Tajikistan', 									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '222',    'code' => 'TK', 'name' => 'Tokelau',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '223',    'code' => 'TL', 'name' => 'East Timor', 									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '224',    'code' => 'TM', 'name' => 'Turkmenistan',   								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '225',    'code' => 'TN', 'name' => 'Tunisia',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '226',    'code' => 'TO', 'name' => 'Tonga',  										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '227',    'code' => 'TR', 'name' => 'Turkey', 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '228',    'code' => 'TT', 'name' => 'Trinidad and Tobago',    						'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '229',    'code' => 'TV', 'name' => 'Tuvalu', 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '230',    'code' => 'TW', 'name' => 'Taiwan', 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '231',    'code' => 'TZ', 'name' => 'Tanzania',   									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '232',    'code' => 'UA', 'name' => 'Ukraine',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '233',    'code' => 'UG', 'name' => 'Uganda', 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '234',    'code' => 'UM', 'name' => 'United States Minor Outlying Islands',   		'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '235',    'code' => 'US', 'name' => 'United States',  								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '236',    'code' => 'UY', 'name' => 'Uruguay',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '237',    'code' => 'UZ', 'name' => 'Uzbekistan', 									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '238',    'code' => 'VA', 'name' => 'Vatican',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '239',    'code' => 'VC', 'name' => 'Saint Vincent and the Grenadines',   			'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '240',    'code' => 'VE', 'name' => 'Venezuela',  									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '241',    'code' => 'VG', 'name' => 'British Virgin Islands', 						'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '242',    'code' => 'VI', 'name' => 'U.S. Virgin Islands',    						'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '243',    'code' => 'VN', 'name' => 'Vietnam',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '244',    'code' => 'VU', 'name' => 'Vanuatu',   	 									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '245',    'code' => 'WF', 'name' => 'Wallis and Futuna', 	 							'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '246',    'code' => 'WS', 'name' => 'Samoa',  										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '247',    'code' => 'XK', 'name' => 'Kosovo', 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '248',    'code' => 'YE', 'name' => 'Yemen',  										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '249',    'code' => 'YT', 'name' => 'Mayotte',    									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '250',    'code' => 'ZA', 'name' => 'South Africa',   								'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '251',    'code' => 'ZM', 'name' => 'Zambia', 										'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('id' => '252',    'code' => 'ZW', 'name' => 'Zimbabwe',  	 									'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL)
        );
        DB::table('countries')->insert($countries);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('countries');
    }
}
