<?php

    /**   DO NOT EDIT THIS FILE!!!   **/

    /*
    |--------------------------------------------------------------------------
    | Permissions
    |--------------------------------------------------------------------------
    |
    | This file is for storing the permissions for the framework.
    | Permissions serve the purpose of giving roles permission to perform
    | specific actions. This way, there is no need to know where to edit code
    | each time a role needs access to a specific action.
    |
    | A permission must have the 'roles' property. Otherwise, it's not taken
    | into account. This way, you can group permissions as you like.
    | Properties other than 'roles' are optional and serve no specific purpose.
    |
    | Project permissions should be placed in their own project permissions
    | file in the 'config/permissions' folder.
    | The file name should be the project path in dot notation.
    |
    | IMPORTANT NOTES
    | - Permission keys must be unique. Otherwise, an exception will be thrown.
    | - This file should only contain global permissions!
    */


$globalPermissions = include "permissions/global.php";
$projectPath = project_path(true);
$projectPermissionsFilePath = "permissions/$projectPath.php";
$projectPermissions = include $projectPermissionsFilePath;

if( empty($projectPermissions) ){
    throw new Exception("Invalid project permissions file: $projectPermissionsFilePath");
}

return array_merge($globalPermissions, $projectPermissions);
